name: DevOps Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: company-backend
  ACCOUNT_ID: 723300665580

jobs:

# ---------------- BUILD ----------------

  build:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/aws-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Create ECR Repository if not exists
        run: |
          aws ecr describe-repositories --repository-names $ECR_REPOSITORY || \
          aws ecr create-repository --repository-name $ECR_REPOSITORY

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS \
          --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker Image
        run: docker build -t $ECR_REPOSITORY ./backend

      - name: Tag Image
        run: |
          docker tag $ECR_REPOSITORY:latest \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Push Image
        run: |
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest


# ---------------- TERRAFORM APPLY ----------------

  terraform:
    name: Create EC2 Infrastructure
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/aws-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Upload Terraform State
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: terraform/terraform.tfstate


# ---------------- DEPLOY ----------------

  deploy:
    name: Deploy to Kubernetes
    needs: terraform
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/aws-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy using SSM
        run: |

          INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=company-k8s-server" \
          --query "Reservations[*].Instances[*].InstanceId" \
          --output text)

          aws ssm send-command \
          --instance-ids $INSTANCE_ID \
          --document-name "AWS-RunShellScript" \
          --parameters commands="[
          'curl -o /tmp/deployment.yaml https://raw.githubusercontent.com/iam-deeppanada/company-website/main/backend/k8/deployment.yaml',
          'sudo kubectl apply -f /tmp/deployment.yaml'
          ]"


# ---------------- DESTROY ----------------

  destroy:
    name: Destroy Infrastructure
    needs: deploy
    runs-on: ubuntu-latest
    environment: destroy-env

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/aws-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Download Terraform State
        uses: actions/download-artifact@v4
        with:
          name: terraform-state
          path: terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: terraform

      - name: Delete ECR Repository
        run: |
          aws ecr delete-repository \
          --repository-name $ECR_REPOSITORY \
          --force