name: CI-CD with SSM Deployment

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: company-backend
  ACCOUNT_ID: 689593414482
  INSTANCE_ID: i-0f7d46c4a2ee740ad

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t company-backend ./backend


  test:
    name: Test Container Build
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test Container
        run: |
          docker build -t company-backend ./backend
          docker run -d -p 5000:5000 --name test-container company-backend
          sleep 5
          curl -f http://localhost:5000 || exit 1
          docker stop test-container
          docker rm test-container


  push:
    name: Push Image to ECR
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and Push Image
        run: |
          docker build -t $ECR_REPOSITORY ./backend
          docker tag $ECR_REPOSITORY:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest


  approval:
    name: Manual Approval
    needs: push
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Waiting for approval
        run: echo "Waiting for approval before deployment"


  deploy:
    name: Deploy to EC2 via SSM
    needs: approval
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy using SSM
        run: |
          aws ssm send-command \
          --instance-ids ${{ env.INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy container via SSM" \
          --parameters commands="[
          'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com',
          'docker pull $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest',
          'docker stop company-backend || true',
          'docker rm company-backend || true',
          'docker run -d -p 5000:5000 --name company-backend $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest'
          ]"